### ISSUE TITLE
Move punctuation marks inside quotes

### ISSUE THREAD

**Issue by Gragt** [jdecock/hugh-lofting_the-voyages-of-doctor-dolittle#2]
A few punctuation marks are outside quotes. They can easily be found and fixed with the `se interactive-replace "’([\.\,])" "\1’" .` command—all changes should be accepted.

**Comment by jdecock** [comment]
Actually, I forgot that I was going to ask about those specifically because if you look [at the source](https://archive.org/details/voyagesofdoctord00loft/page/202/mode/2up), it's several sentence fragments separated by four periods. The periods aren't inside the quotation marks and it seems like the better way to handle it would be to remove the 4th period and leave the ellipsis that are added by `typogrify`. Thoughts?

**Comment by Gragt** [comment]
Rules vary a lot across editions and through time; that’s why we have ours to help make sense of it all. :)

It seems the book uses only three dots for ellipses (you can see it [in the middle of p. 212](https://archive.org/details/voyagesofdoctord00loft/page/212/mode/2up)), so one of  dots in a series of four should be a full-stop—that it isn’t inside quotes is down to whatever rules the publisher was using. It makes sense: the character is listening and repeating whatever he can understand, pausing between each fragment.

Because each fragment can stand on its own, I would keep the punctuation but inside quotes. That said, the way you describe could also work. I don’t think either would make a huge difference so how about you try them both and decide which one looks best? If you do decide to remove the full-stops, better make it an [Editorial] commit since that would modify the content.

**Comment by jdecock** [comment]
After looking at it more, it does seem reasonable for there to be a full stop at the end of each phrase. I've made that change.
